modLoader="javafml"
loaderVersion="[26,)"
license="GNU GENERAL PUBLIC LICENSE Version 3"
issueTrackerURL="https://github.com/ichttt/Eternal-Winter/issues"

[[mods]]
    modId="eternalwinter"
    version="${file.jarVersion}"
    displayName="Eternal Winter"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/eternal-winter"
    authors="ichttt"
    description='''Eternal Winter is a small mod that enables snow in every biome'''
#[[dependencies.eternalwinter]]
#    modId="forge"
#    mandatory=true
#    versionRange="[34.1.0,)"
#    ordering="NONE"
#    side="BOTH"
[[dependencies.eternalwinter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
